return {
  ["Cake Queen Place [Throne]"] = {-296, 208, 9253},
  ["Dragon Spawner [ORB]"] = {-6009, 462, 7304},
  ["Dead Tundra [Desert Island]"] = {2648, 226, 1492},
  ["Shred... [Hot and Cold]"] = {-221, 87, -2598},
  ["Marine Basement [Fujitora]"] = {-10543, 603, 1120},
  ["Traveler [Sea 1]"] = {-3351, 17, 252},
  ["King Samurai [Japanese Base]"] = {-5636, 383, -12},
  ["GreenZone [Tree]"] = {9353, 72, -4296},
  ["Fiore [Dressrosa]"] = {6545, 419, -3100},
  ["Dungeon [Raid]"] = {-2439, 373, -1492},
  ["Dark Beard Spawner [Totem]"] = {-9449, 77, -5107},
  ["Traveler [Sea 3]"] = {-8062, 34, 3206}
}
